use_frameworks!

target 'DottedProgressBar_Example' do
  pod 'DottedProgressBar', :path => '../'

  target 'DottedProgressBar_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
